services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: FLASK_ENV
        value: production
